fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Sonata\UserBundle\Entity\BaseUser
    
    group:
        group_class: Sonata\UserBundle\Entity\BaseGroup
        group_manager: sonata.user.orm.group_manager
        
    service:
        user_manager: sonata.user.orm.user_manager
        mailer: fos_user.mailer.twig_swift
        
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"